void setupFloat();
void deployFloat();
void startFloat();
void stopFloat();
void logData();
float convertSensorValue(int seconds);
void displayData();
bool floatDeployed();
void displayPacket();
float pressureToDepth(float pressure);