void setupFloat();
void deployFloat();
void returnFloat(int returnStartTime);
void startFloat();
void stopFloat();
void logData();
float convertSensorValue();
void displayData();
bool floatDeployed();
void displayPacket();
float pressureToDepth(float pressure);